#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
# set -x

APP="$1"; IMAGE=$(get_app_image_name $APP)

id=$(docker run -d $IMAGE /bin/bash -c "/app/.builders_run")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null

dokku_log_info1 "Builders complete"
